spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  #      h2 DB를 임시로 생성하여 사용할 수 있다.
  datasource:
    url: jdbc:h2:mem:islog
    username: sa
    password:
    driver-class-name: org.h2.Driver